Move proxy code to an example
tweag/nix-remote-rust pull request #5
Opened 2024-10-28 15:17 UTC by YorikSar

It is an example, after all, and it feels like it belongs in a separate space.

cc @jneem

2024-10-28 16:07 UTC, jneem requested changes

2024-10-28 16:07 UTC, jneem commented on src/lib.rs
> -    pub fn handshake(&mut self) -> Result<u64> {
I agree with most of this PR, and clearly the public API here needs some thought, but we're actually using this function [elsewhere](https://github.com/tweag/remote-execution-nix/blob/d7b21a7aa54b6ed5482ad2b09662d880fef2fc6d/crates/proxy/src/main.rs#L530) so I think it makes sense to have it in the library.

2024-10-28 16:13 UTC, YorikSar commented on src/lib.rs
> -    pub fn handshake(&mut self) -> Result<u64> {
Oh, I see you’re using NixProxy and some of its methods there. I’ll think about extracting some reusable API subset from it.

2024-10-31 16:14 UTC, YorikSar commented
I've started extracting all interfaces in https://github.com/tweag/nix-remote-rust/pull/8 keeping in mind [remote-execution-nix](https://github.com/tweag/remote-execution-nix/blob/d7b21a7aa54b6ed5482ad2b09662d880fef2fc6d/crates/proxy/src/main.rs#L530) requirements.

2024-11-05 11:32 UTC, YorikSar commented
Closed in favour of #7

2024-11-05 11:32 UTC, closed without merging